### ISSUE TITLE
Ignored configuration directories should be removed

### ISSUE THREAD

**Issue by SmedbergM** [jetbrains-academy/Functional_Programming_Scala#38]
The repository's `.gitignore` file excludes the `.bsp` and `.idea` directories. However, early versions of these directories got committed from @kajigor's local configuration.

**Comment by SmedbergM** [comment]
Also there are a lot of `target/` directories under version control which shouldn't be.

**Comment by kajigor** [comment]
@SmedbergM Thanks for the fix.
